---
- name: Telegram benchmark for 15 minutes
  hosts: localhost
  gather_facts: no
  vars:
    telegram_token: "SEU_TOKEN_AQUI"
    chat_id: "SEU_CHAT_ID_AQUI"
    duration_minutes: 15
    interval_seconds: 60
    iterations: "{{ (duration_minutes * 60 / interval_seconds) | int }}"

  tasks:
    - name: Notify start
      uri:
        url: "https://api.telegram.org/bot{{ telegram_token }}/sendMessage"
        method: POST
        body_format: json
        body:
          chat_id: "{{ chat_id }}"
          text: "🚀 Benchmark iniciado! Vai rodar por {{ duration_minutes }} minutos com {{ iterations }} iterações."
      delegate_to: localhost

    - name: Run benchmark iteration
      include_tasks: benchmark_iteration.yml
      loop: "{{ range(1, iterations + 1) | list }}"
      loop_control:
        loop_var: idx

    - name: Send final summary
      command: bash -c "grep -c OK /tmp/telegram_benchmark.log || true"
      register: ok_count

    - name: Count total tests
      command: bash -c "wc -l /tmp/telegram_benchmark.log | awk '{print $1}'"
      register: total_count

    - name: Notify com
